### ISSUE TITLE
User Story 6: Familiarity and usability

### ISSUE THREAD

**Issue by Leo-gwe** [Leo-gwe/JSQuiz#1]
**User Story 6: Appearance and usability**:
As a regular quiz user I want to be presented with a single screen quiz which is familiar, intuitive and logical in layout to me so that I can easily operate the quiz and navigate the site.

**Acceptance Criteria:**
- [ ] The layout should be logical, familiar and intuitive
- [ ] The quiz function should be similar to other quiz sites
- [ ] A next question button will be used to give the user control on the flow of the quiz.
- [ ] A reset/retry button is present to allow the user to try again
- [ ] The user can track how many questions they have answered and how many they have left to answer
- [ ] The site should have an attractive hero image/background which is suitable for the subject matter.

**Tasks:**
- [ ] Use HTML, CSS and Bootstrap to create a page which is laid out in a logical manner
- [ ] Research other quiz sites and utilise similar layouts
- [ ] Code a next question button
- [ ] Code a reset/retry button
- [ ] Code a question counter section
- [ ] Locate/create image in WebP format for background/hero.
